@ProjectTaskManagement.Api_HostAddress = http://localhost:5113
@Token = paste-jwt-token-here

POST {{ProjectTaskManagement.Api_HostAddress}}/api/v1/auth/register
Content-Type: application/json

{
  "fullName": "Mahmoud Mostafa Desoky Ahmed",
  "email": "mahmoud@example.com",
  "password": "Password1"
}

###

POST {{ProjectTaskManagement.Api_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "mahmoud@example.com",
  "password": "Password1"
}

###

GET {{ProjectTaskManagement.Api_HostAddress}}/api/v1/projects
Authorization: Bearer {{Token}}

###

POST {{ProjectTaskManagement.Api_HostAddress}}/api/v1/projects
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "name": "Technical Test Project",
  "description": "Project management API submission"
}
